# Generated by Django 4.1.4 on 2022-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(choices=[('X', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='M', max_length=2),
        ),
    ]
