# Generated by Django 4.1.4 on 2022-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_size_orderplaced_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='null'),
        ),
    ]
